#!/bin/bash
# =============================================================================
# Snowflake Quickstart Setup
# =============================================================================
# One-command setup for testing SalesInsight with your Snowflake account.
#
# What this does:
#   1. Checks prerequisites (Python, Node.js)
#   2. Prompts for Snowflake + Azure OpenAI credentials
#   3. Validates Snowflake connectivity
#   4. Creates .env file
#   5. Installs dependencies
#   6. Starts the application
#
# Usage:
#   ./scripts/quickstart_snowflake.sh
#   ./scripts/quickstart_snowflake.sh --local   # Use local CSV instead of Snowflake
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_DIR"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

USE_LOCAL=false
for arg in "$@"; do
    case $arg in
        --local)
            USE_LOCAL=true
            shift
            ;;
    esac
done

echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║       SalesInsight - Snowflake Quickstart Setup           ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# =============================================================================
# Step 1: Check Prerequisites
# =============================================================================
echo -e "${BLUE}[1/6] Checking prerequisites...${NC}"

MISSING=()

if ! command -v python3 &> /dev/null && ! command -v python &> /dev/null; then
    MISSING+=("Python 3.10+ (https://python.org)")
fi

if ! command -v node &> /dev/null; then
    MISSING+=("Node.js 18+ (https://nodejs.org)")
fi

if [ ${#MISSING[@]} -gt 0 ]; then
    echo -e "${RED}Missing required tools:${NC}"
    for tool in "${MISSING[@]}"; do
        echo -e "  ${RED}✗${NC} $tool"
    done
    exit 1
fi

PYTHON_CMD="python3"
command -v python3 &> /dev/null || PYTHON_CMD="python"
PYTHON_VERSION=$($PYTHON_CMD --version 2>&1 | grep -oE '[0-9]+\.[0-9]+')
NODE_VERSION=$(node --version 2>&1)
echo -e "  ${GREEN}✓${NC} Python $PYTHON_VERSION"
echo -e "  ${GREEN}✓${NC} Node.js $NODE_VERSION"

# Check for poetry (optional, falls back to pip)
HAS_POETRY=false
if command -v poetry &> /dev/null; then
    HAS_POETRY=true
    echo -e "  ${GREEN}✓${NC} Poetry $(poetry --version 2>&1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')"
fi

echo ""

# =============================================================================
# Step 2: Collect Credentials
# =============================================================================
echo -e "${BLUE}[2/6] Collecting credentials...${NC}"
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
    echo -e "${YELLOW}  A .env file already exists.${NC}"
    read -r -p "  Overwrite it? (y/N): " OVERWRITE
    if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
        echo -e "  ${GREEN}✓${NC} Keeping existing .env"
        SKIP_ENV=true
    else
        SKIP_ENV=false
    fi
else
    SKIP_ENV=false
fi

if [ "$SKIP_ENV" = false ]; then
    if [ "$USE_LOCAL" = false ]; then
        echo -e "${BOLD}  Snowflake Connection${NC}"
        echo -e "  (See docs/snowflake_setup.md for table setup)"
        echo ""
        read -r -p "  Snowflake Account (e.g. xy12345.us-east-1): " SF_ACCOUNT
        read -r -p "  Snowflake User: " SF_USER
        read -r -s -p "  Snowflake Password: " SF_PASSWORD
        echo ""
        read -r -p "  Snowflake Warehouse [COMPUTE_WH]: " SF_WAREHOUSE
        SF_WAREHOUSE=${SF_WAREHOUSE:-COMPUTE_WH}
        read -r -p "  Snowflake Database [SALES_DB]: " SF_DATABASE
        SF_DATABASE=${SF_DATABASE:-SALES_DB}
        read -r -p "  Snowflake Schema [ORDERS]: " SF_SCHEMA
        SF_SCHEMA=${SF_SCHEMA:-ORDERS}
        read -r -p "  Snowflake Role (optional): " SF_ROLE
        echo ""
    fi

    echo -e "${BOLD}  Azure OpenAI${NC}"
    echo -e "  (Get from Azure Portal > Azure OpenAI > Keys and Endpoint)"
    echo ""
    read -r -p "  Azure OpenAI Resource Name: " AOAI_RESOURCE
    read -r -s -p "  Azure OpenAI API Key: " AOAI_KEY
    echo ""
    read -r -p "  Model Deployment Name [gpt-4o]: " AOAI_MODEL
    AOAI_MODEL=${AOAI_MODEL:-gpt-4o}
    echo ""

    # Write .env
    echo -e "${BLUE}  Writing .env file...${NC}"
    cat > .env << ENVEOF
# Generated by quickstart_snowflake.sh on $(date +%Y-%m-%d)

# Snowflake
SNOWFLAKE_ACCOUNT=${SF_ACCOUNT:-}
SNOWFLAKE_USER=${SF_USER:-}
SNOWFLAKE_PASSWORD=${SF_PASSWORD:-}
SNOWFLAKE_WAREHOUSE=${SF_WAREHOUSE:-COMPUTE_WH}
SNOWFLAKE_DATABASE=${SF_DATABASE:-SALES_DB}
SNOWFLAKE_SCHEMA=${SF_SCHEMA:-ORDERS}
SNOWFLAKE_ROLE=${SF_ROLE:-}
SALESINSIGHT_USE_LOCAL_DATA=${USE_LOCAL}

# Azure OpenAI
AZURE_OPENAI_RESOURCE=${AOAI_RESOURCE}
AZURE_OPENAI_API_KEY=${AOAI_KEY}
AZURE_OPENAI_MODEL=${AOAI_MODEL}
AZURE_OPENAI_MODEL_NAME=${AOAI_MODEL}
AZURE_OPENAI_EMBEDDING_MODEL=text-embedding-ada-002
AZURE_OPENAI_TEMPERATURE=0
AZURE_OPENAI_MAX_TOKENS=1000
AZURE_OPENAI_API_VERSION=2024-02-01
AZURE_OPENAI_STREAM=True
AZURE_AUTH_TYPE=keys

# Orchestration
ORCHESTRATION_STRATEGY=openai_function
CONVERSATION_FLOW=custom

# Backend
BACKEND_URL=http://localhost:7071
LOGLEVEL=INFO

# Leave empty to skip document RAG features (Snowflake NL2SQL still works)
AZURE_SEARCH_SERVICE=
AZURE_SEARCH_KEY=
AZURE_SEARCH_INDEX=
AZURE_BLOB_ACCOUNT_NAME=
AZURE_BLOB_ACCOUNT_KEY=
AZURE_BLOB_CONTAINER_NAME=documents
ENVEOF

    echo -e "  ${GREEN}✓${NC} .env created"
fi

echo ""

# =============================================================================
# Step 3: Validate Snowflake Connection
# =============================================================================
if [ "$USE_LOCAL" = false ]; then
    echo -e "${BLUE}[3/6] Testing Snowflake connection...${NC}"

    # Source .env for the test
    set -a
    source .env
    set +a

    # Quick Python connectivity check (only needs snowflake-connector-python)
    VENV_PYTHON="$PROJECT_DIR/.venv/bin/python"
    if [ ! -f "$VENV_PYTHON" ]; then
        # Create a minimal venv for the test
        $PYTHON_CMD -m venv .venv 2>/dev/null
        VENV_PYTHON="$PROJECT_DIR/.venv/bin/python"
        "$PROJECT_DIR/.venv/bin/pip" install --quiet snowflake-connector-python 2>&1 | tail -1
    fi

    # Check if snowflake-connector is installed, install if not
    if ! "$VENV_PYTHON" -c "import snowflake.connector" 2>/dev/null; then
        echo -e "  ${YELLOW}Installing Snowflake connector...${NC}"
        "$PROJECT_DIR/.venv/bin/pip" install --quiet snowflake-connector-python 2>&1 | tail -1
    fi

    SF_TEST=$("$VENV_PYTHON" -c "
import os, sys
try:
    import snowflake.connector
    conn = snowflake.connector.connect(
        account=os.environ['SNOWFLAKE_ACCOUNT'],
        user=os.environ['SNOWFLAKE_USER'],
        password=os.environ['SNOWFLAKE_PASSWORD'],
        warehouse=os.environ.get('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH'),
        database=os.environ.get('SNOWFLAKE_DATABASE', 'SALES_DB'),
        schema=os.environ.get('SNOWFLAKE_SCHEMA', 'ORDERS'),
        login_timeout=15,
    )
    cur = conn.cursor()
    cur.execute('SELECT COUNT(*) FROM ORDERHISTORYLINE')
    count = cur.fetchone()[0]
    conn.close()
    print(f'OK:{count}')
except Exception as e:
    print(f'FAIL:{e}')
" 2>&1)

    if [[ "$SF_TEST" == OK:* ]]; then
        ROW_COUNT="${SF_TEST#OK:}"
        echo -e "  ${GREEN}✓${NC} Connected to Snowflake — ${ROW_COUNT} rows in ORDERHISTORYLINE"
    else
        ERROR_MSG="${SF_TEST#FAIL:}"
        echo -e "  ${RED}✗${NC} Snowflake connection failed: ${ERROR_MSG}"
        echo ""
        echo -e "  ${YELLOW}Common fixes:${NC}"
        echo "    - Check account format: xy12345.us-east-1"
        echo "    - Verify warehouse is started in Snowflake UI"
        echo "    - Confirm database/schema/table exist (see docs/snowflake_setup.md)"
        echo ""
        read -r -p "  Continue anyway? (y/N): " CONTINUE
        if [[ ! "$CONTINUE" =~ ^[Yy]$ ]]; then
            echo "  Exiting. Fix credentials and re-run this script."
            exit 1
        fi
    fi
else
    echo -e "${BLUE}[3/6] Local CSV mode — skipping Snowflake check${NC}"
    if [ -f "data/db_more_weu_prod_dbo_OrderHistoryLine.csv" ]; then
        ROW_COUNT=$(wc -l < "data/db_more_weu_prod_dbo_OrderHistoryLine.csv" | tr -d ' ')
        echo -e "  ${GREEN}✓${NC} Found local CSV with ~${ROW_COUNT} rows"
    else
        echo -e "  ${YELLOW}⚠${NC} No CSV found in data/. Place your OrderHistoryLine CSV there."
    fi
fi

echo ""

# =============================================================================
# Step 4: Install Dependencies
# =============================================================================
echo -e "${BLUE}[4/6] Installing dependencies...${NC}"

# Python
if [ ! -d ".venv" ]; then
    echo -e "  ${YELLOW}Creating Python virtual environment...${NC}"
    $PYTHON_CMD -m venv .venv
fi

VENV_PYTHON="$PROJECT_DIR/.venv/bin/python"
VENV_PIP="$PROJECT_DIR/.venv/bin/pip"

if [ "$HAS_POETRY" = true ]; then
    echo -e "  ${BLUE}Installing Python packages via poetry...${NC}"
    poetry config virtualenvs.in-project true 2>/dev/null || true
    poetry install --no-interaction 2>&1 | grep -E "(Installing|Already)" | tail -5 || true
else
    echo -e "  ${BLUE}Installing Python packages via pip...${NC}"
    $VENV_PIP install --quiet --upgrade pip 2>/dev/null
    $VENV_PIP install --quiet -e ".[dev]" 2>&1 | tail -3 || \
    $VENV_PIP install --quiet \
        "flask[async]>=3.1.2" \
        "openai>=1.109.1" \
        "python-dotenv>=1.1.1" \
        "snowflake-connector-python>=3.6.0" \
        "pandas>=2.3.3" \
        "azure-identity>=1.25.0" \
        "azure-storage-blob>=12.26.0" \
        "azure-search-documents>=11.6.0b1" \
        "streamlit>=1.50.0" \
        "tiktoken>=0.11.0" \
        "matplotlib>=3.10.3" \
        "pydantic>=2.11.9" \
        2>&1 | tail -3
fi
echo -e "  ${GREEN}✓${NC} Python dependencies installed"

# Node.js
echo -e "  ${BLUE}Installing frontend packages...${NC}"
cd code/frontend && npm install --silent 2>&1 | tail -1 && cd ../..
echo -e "  ${GREEN}✓${NC} Frontend dependencies installed"

echo ""

# =============================================================================
# Step 5: Start Services
# =============================================================================
echo -e "${BLUE}[5/6] Starting services...${NC}"
echo ""

# Activate venv for subprocesses
export PATH="$PROJECT_DIR/.venv/bin:$PATH"

# Source .env
set -a
source .env
set +a

# Flask API
echo -e "  Starting Flask API (port 5050)..."
cd "$PROJECT_DIR/code"
"$VENV_PYTHON" app.py > /tmp/salesinsight-flask.log 2>&1 &
FLASK_PID=$!
cd "$PROJECT_DIR"

# Vite dev server
echo -e "  Starting frontend (port 5173)..."
cd "$PROJECT_DIR/code/frontend"
npx vite --host 2>/dev/null > /tmp/salesinsight-vite.log 2>&1 &
VITE_PID=$!
cd "$PROJECT_DIR"

# Wait for Flask to start
sleep 3

# Quick health check
if kill -0 $FLASK_PID 2>/dev/null; then
    echo -e "  ${GREEN}✓${NC} Flask API running (PID $FLASK_PID)"
else
    echo -e "  ${RED}✗${NC} Flask failed to start. Check /tmp/salesinsight-flask.log"
fi

if kill -0 $VITE_PID 2>/dev/null; then
    echo -e "  ${GREEN}✓${NC} Frontend running (PID $VITE_PID)"
else
    echo -e "  ${RED}✗${NC} Frontend failed to start. Check /tmp/salesinsight-vite.log"
fi

echo ""

# =============================================================================
# Step 6: Done!
# =============================================================================
echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                    Ready to go!                           ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Open in your browser:${NC}  http://localhost:5173"
echo ""
echo -e "  ${BOLD}Try asking:${NC}"
echo "    \"What are the top 10 products by revenue?\""
echo "    \"Show me turnover by region for FY 25/26\""
echo "    \"Which customers have the highest order volume?\""
echo ""
echo -e "  ${BOLD}Stop everything:${NC}  ./stop_local.sh"
echo ""
echo -e "  ${BOLD}Logs:${NC}"
echo "    Flask:    tail -f /tmp/salesinsight-flask.log"
echo "    Frontend: tail -f /tmp/salesinsight-vite.log"
echo ""
